#!/bin/bash

curl http://www.joystiq.com/rss.xml > joystiq.xml 2>/dev/null 

DONE=false;

function readpage {
    read STRING || DONE=true;
    [[ ! $STRING ]] && continue;
    # echo "Another string read:";
    # echo $STRING;
    # Now print line if it matches the required format
    eval COUNT=$(echo $STRING | grep -c "<title><\!\[CDATA\[")

    if [ $COUNT -eq 1 ] 
    then
        HEADLINE=$(echo $STRING | awk -F"]" '{print $1}' | awk -F"[" '{print $3}');
        echo '-'$HEADLINE
    fi
}

until $DONE ; do
    readpage;
    if [ -z "$STRING" ]
    then
        echo "ran out of lines"
        rm joystiq.xml
        exit
    fi
done < joystiq.xml
