#!/bin/bash

curl http://www.joystiq.com/rss.xml > joystiq.xml 2>/dev/null 

function readpage {
    read STRING;
    # Now print line if it matches the required format
    eval COUNT=$(echo $STRING | grep -c "<title><\!\[CDATA\[")


    if [ $COUNT -eq 1 ] 
    then
        HEADLINE=$(echo $STRING | awk -F"]" '{print $1}' | awk -F"[" '{print $3}');
        echo '-'$HEADLINE
    fi
}

while readpage; do
    if [ -z "$STRING" ]
    then
        rm joystiq.xml
        exit
    fi
done < joystiq.xml
